version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm i -g npm@latest'
      - run:
          name: install yarn
          command: 'sudo npm i -g yarn@latest'

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: npm-install
          command: npm install

      # In your code, add this (after installing with `npm install --save-dev audit-ci`):
      # - run:
      #    name: run-audit-ci
      #    command: 'audit-ci --moderate'

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Have audit-ci run audit-ci to audit itself :)
      - run:
          name: run-audit-ci
          command: node lib/audit-ci.js -l --config ./audit-ci.json

      - run:
          name: run-lint
          command: npm run lint

      - run:
          name: run-tests
          command: npm run test
