version: 2
jobs:
  build:
    docker:
      - image: cimg/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7

      - run:
          name: pnpm-install
          command: pnpm install

      # In your code, add this (after installing with `pnpm install --save-dev audit-ci`):
      # - run:
      #    name: run-audit-ci
      #    command: 'audit-ci --moderate'

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: run-build
          command: pnpm run build

      # Have audit-ci run audit-ci to audit itself :)
      - run:
          name: run-audit-ci
          # Only have audit-ci checks on pull requests
          command: if [[ ! -z $CIRCLE_PULL_REQUEST ]]; then node dist/audit-ci.js --config ./audit-ci.jsonc; fi
      - run:
          name: run-lint
          command: pnpm run lint

      - run:
          name: run-tests
          command: pnpm run test
