version: 2
jobs:
  build:
    docker:
      - image: cimg/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: npm-install
          command: npm install

      # In your code, add this (after installing with `npm install --save-dev audit-ci`):
      # - run:
      #    name: run-audit-ci
      #    command: 'audit-ci --moderate'

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: run-build
          command: npm run build

      # Have audit-ci run audit-ci to audit itself :)
      - run:
          name: run-audit-ci
          # Only have audit-ci checks on pull requests
          command: if [[ ! -z $CIRCLE_PULL_REQUEST ]]; then node dist/audit-ci.js --config ./audit-ci.jsonc; fi
      - run:
          name: run-lint
          command: npm run lint

      - run:
          name: run-tests
          command: npm run test
