#!/usr/bin/env node
const path = require('path');

const errorMessagePath = path.resolve(__dirname, 'error-message.js');
const errorMessage = require(errorMessagePath); //eslint-disable-line

console.error(errorMessage);
process.exitCode = 1;
