# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build and test
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "18", "20"]
    name: Build and test with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - uses: oven-sh/setup-bun@v1
      - run: npm ci
      - run: bun run build
      # Have audit-ci run audit-ci to audit itself :)
      - run: bun ./dist/bin.js --config ./audit-ci.jsonc
      - run: bun run test
      - run: bun run lint
      - run: bun run format -- --check
