# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build and test
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14", "16"]
    name: Build and test with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - run: pnpm run build
      # Have audit-ci run audit-ci to audit itself :)
      - run: node ./dist/audit-ci.js --config ./audit-ci.jsonc
      - run: pnpm run test
      - run: pnpm run lint
      - run: pnpm run format -- --check
